[project]
name = "paperworkflow"
version = "0.1.0"
description = "小仓库"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.4.1",
    "openai>=2.15.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "tokenizers>=0.22.2",
    "tqdm>=4.67.1",
]
